name: CI
on:
  push:
    branches:
      - main
jobs:
  deployment:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          keys: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            whoami
            cd /root/webapp-cicd
            git pull origin main
            docker compose up --build -d
